// springboot-payment-v1/payment-demo-java/payment-demo-react/src/pages/Download.jsx
import { Button, DatePicker, Form, message } from 'antd'

import billApi from '@/api/bill'

function triggerDownload(url, filename) {
  const element = document.createElement('a')
  element.setAttribute('href', url)
  element.setAttribute('download', filename)
  element.style.display = 'none'
  document.body.appendChild(element)
  element.click()
  document.body.removeChild(element)
}

export default function Download() {
  const [wxForm] = Form.useForm()
  const [aliForm] = Form.useForm()

  const downloadBill = (type) => {
    const billDate = wxForm.getFieldValue('billDate')?.format('YYYY-MM-DD')
    if (!billDate) {
      message.warning('请选择微信账单日期')
      return
    }

    billApi.downloadBillWxPay(billDate, type).then((response) => {
      const content = response?.data?.result || ''
      triggerDownload(
        `data:application/vnd.ms-excel;charset=utf-8,${encodeURIComponent(content)}`,
        `${billDate}-${type}`
      )
    })
  }

  const downloadBillAliPay = (type) => {
    const billDate = aliForm.getFieldValue('billDate')?.format('YYYY-MM-DD')
    if (!billDate) {
      message.warning('请选择支付宝账单日期')
      return
    }

    billApi.downloadBillAliPay(billDate, type).then((response) => {
      const downloadUrl = response?.data?.downloadUrl
      if (!downloadUrl) {
        message.error('未获取到账单下载地址')
        return
      }
      triggerDownload(downloadUrl, `${billDate}-${type}`)
    })
  }

  return (
    <div className="bg-fa of">
      <section id="index" className="container">
        <header className="comm-title">
          <h2 className="fl tac">
            <span className="c-333">微信账单申请</span>
          </h2>
        </header>

        <Form form={wxForm} layout="inline">
          <Form.Item name="billDate">
            <DatePicker placeholder="选择账单日期" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={() => downloadBill('tradebill')}>下载交易账单</Button>
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={() => downloadBill('fundflowbill')}>下载资金账单</Button>
          </Form.Item>
        </Form>
      </section>

      <section id="index" className="container">
        <header className="comm-title">
          <h2 className="fl tac">
            <span className="c-333">支付宝账单申请</span>
          </h2>
        </header>

        <Form form={aliForm} layout="inline">
          <Form.Item name="billDate">
            <DatePicker placeholder="选择账单日期" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={() => downloadBillAliPay('trade')}>下载交易账单</Button>
          </Form.Item>
          <Form.Item>
            <Button type="primary" onClick={() => downloadBillAliPay('signcustomer')}>下载资金账单</Button>
          </Form.Item>
        </Form>
      </section>
    </div>
  )
}

// springboot-payment/payment-demo-java/payment-demo-vue/src/views/Download.vue
<template>
  <div class="bg-fa of">
    <section id="index" class="container">
      <header class="comm-title">
        <h2>微信账单申请</h2>
      </header>
      
      <div class="bill-section">
        <el-form :inline="true" class="bill-form">
          <el-form-item>
              <el-date-picker v-model="billDate" value-format="yyyy-MM-dd" placeholder="选择账单日期" />
          </el-form-item>
          <el-form-item>
              <el-button type="primary" @click="downloadBill('tradebill')">下载交易账单</el-button>
          </el-form-item>
           <el-form-item>
              <el-button type="primary" @click="downloadBill('fundflowbill')">下载资金账单</el-button>
          </el-form-item>
        </el-form>
      </div>
    </section>

    <section id="index" class="container">
      <header class="comm-title">
        <h2>支付宝账单申请</h2>
      </header>
      
      <div class="bill-section">
        <el-form :inline="true" class="bill-form">
          <el-form-item>
              <el-date-picker v-model="billDate_alipay" value-format="yyyy-MM-dd" placeholder="选择账单日期" />
          </el-form-item>
          <el-form-item>
              <el-button type="primary" @click="downloadBillAliPay('trade')">下载交易账单</el-button>
          </el-form-item>
           <el-form-item>
              <el-button type="primary" @click="downloadBillAliPay('signcustomer')">下载资金账单</el-button>
          </el-form-item>
        </el-form>
      </div>
    </section>

  </div>
</template>

<script>
import billApi from '../api/bill'

export default {
  data () {
    return {
       billDate: '', //微信支付账单日期
       billDate_alipay: '' //支付宝账单日期
    }
  },

  methods: {

    //下载账单：微信支付
    downloadBill(type){
      //获取账单内容
      billApi.downloadBillWxPay(this.billDate, type).then(response => {
        console.log(response)
        const element = document.createElement('a')
        element.setAttribute('href', 'data:application/vnd.ms-excel;charset=utf-8,' + encodeURIComponent(response.data.result))
        element.setAttribute('download', this.billDate + '-' + type)
        element.style.display = 'none'
        element.click()
      })
    },

    //下载账单：支付宝
    downloadBillAliPay(type){
        billApi.downloadBillAliPay(this.billDate_alipay, type).then(response => {
          console.log(response.data.downloadUrl)
          const element = document.createElement('a')
          element.setAttribute('href', response.data.downloadUrl)
          element.setAttribute('download', this.billDate_alipay + '-' + type)
          element.style.display = 'none'
          element.click()
        })
    }
  }
}
</script>
