// springboot-payment/payment-demo-java-dm/payment-demo-vue/src/views/Reconciliation.vue
<template>
  <div class="bg-fa of">
    <section id="index" class="container">
      <header class="comm-title">
        <h2>对账管理</h2>
      </header>

      <el-form :inline="true" :model="queryForm" class="filter-form">
        <el-form-item label="账单日期">
          <el-date-picker
            v-model="queryForm.dateRange"
            type="daterange"
            range-separator="至"
            start-placeholder="开始日期"
            end-placeholder="结束日期"
            value-format="yyyy-MM-dd">
          </el-date-picker>
        </el-form-item>
        <el-form-item label="渠道">
          <el-select v-model="queryForm.channelCode" placeholder="全部渠道" clearable>
            <el-option label="微信支付" value="WXPAY"></el-option>
            <el-option label="支付宝" value="ALIPAY"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="状态">
          <el-select v-model="queryForm.status" placeholder="全部状态" clearable>
            <el-option label="待处理" value="PENDING"></el-option>
            <el-option label="处理中" value="PROCESSING"></el-option>
            <el-option label="已完成" value="COMPLETED"></el-option>
            <el-option label="失败" value="FAILED"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadBatches">查询</el-button>
          <el-button @click="resetQuery">重置</el-button>
          <el-button type="success" @click="openCreateDialog">手动对账</el-button>
        </el-form-item>
      </el-form>

      <el-row :gutter="16" class="summary-row">
        <el-col :span="6">
          <el-card shadow="hover">
            <el-statistic title="今日批次" :value="summary.todayBatchCount || 0"></el-statistic>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <el-statistic title="已完成" :value="summary.todayCompletedCount || 0">
              <template slot="suffix">个</template>
            </el-statistic>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <el-statistic title="失败" :value="summary.todayFailedCount || 0">
              <template slot="suffix">个</template>
            </el-statistic>
          </el-card>
        </el-col>
        <el-col :span="6">
          <el-card shadow="hover">
            <el-statistic title="待处理" :value="summary.pendingDiscrepancyCount || 0">
              <template slot="suffix">个</template>
            </el-statistic>
          </el-card>
        </el-col>
      </el-row>

      <el-table :data="batchList" border style="width: 100%" class="batch-table">
        <el-table-column type="index" width="50" label="序号"></el-table-column>
        <el-table-column prop="batchNo" label="批次号" width="200"></el-table-column>
        <el-table-column prop="channelCode" label="渠道" width="100">
          <template slot-scope="scope">
            {{ channelText(scope.row.channelCode) }}
          </template>
        </el-table-column>
        <el-table-column prop="billDate" label="账单日期" width="120"></el-table-column>
        <el-table-column label="状态" width="100">
          <template slot-scope="scope">
            <el-tag :type="batchStatusTagType(scope.row.status)">
              {{ batchStatusText(scope.row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="channelCount" label="渠道笔数" width="100"></el-table-column>
        <el-table-column prop="localCount" label="本地笔数" width="100"></el-table-column>
        <el-table-column prop="matchedCount" label="匹配笔数" width="100"></el-table-column>
        <el-table-column prop="discrepancyCount" label="差异笔数" width="100"></el-table-column>
        <el-table-column label="操作" width="280" align="center">
          <template slot-scope="scope">
            <el-button
              v-if="scope.row.status === 'PENDING' || scope.row.status === 'FAILED'"
              type="text"
              @click="executeBatch(scope.row)">执行</el-button>
            <el-button type="text" @click="showDetails(scope.row)">明细</el-button>
            <el-button type="text" @click="showDiscrepancies(scope.row)">差异</el-button>
            <el-button type="text" @click="showProgress(scope.row)">进度</el-button>
          </template>
        </el-table-column>
      </el-table>
    </section>

    <el-dialog title="手动创建对账批次" :visible.sync="createDialogVisible" width="500px">
      <el-form :model="createForm" :rules="createRules" ref="createForm" label-width="100px">
        <el-form-item label="渠道" prop="channelCode">
          <el-select v-model="createForm.channelCode" placeholder="请选择渠道" style="width: 100%">
            <el-option label="微信支付" value="WXPAY"></el-option>
            <el-option label="支付宝" value="ALIPAY"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="应用ID" prop="paymentAppId">
          <el-input v-model="createForm.paymentAppId" placeholder="请输入支付应用ID"></el-input>
        </el-form-item>
        <el-form-item label="账单日期" prop="billDate">
          <el-date-picker
            v-model="createForm.billDate"
            type="date"
            placeholder="选择账单日期"
            value-format="yyyy-MM-dd"
            style="width: 100%">
          </el-date-picker>
        </el-form-item>
      </el-form>
      <div slot="footer">
        <el-button @click="createDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitCreate">创建</el-button>
      </div>
    </el-dialog>

    <el-dialog title="对账明细" :visible.sync="detailDialogVisible" width="1100px">
      <el-table :data="detailList" border style="width: 100%">
        <el-table-column type="index" width="50"></el-table-column>
        <el-table-column prop="orderNo" label="订单号" width="200"></el-table-column>
        <el-table-column prop="channelOrderNo" label="渠道订单号" width="200"></el-table-column>
        <el-table-column label="金额" width="120">
          <template slot-scope="scope">
            {{ (scope.row.amount || 0) / 100 }} 元
          </template>
        </el-table-column>
        <el-table-column label="匹配状态" width="100">
          <template slot-scope="scope">
            <el-tag size="mini" :type="matchStatusTagType(scope.row.matchStatus)">
              {{ matchStatusText(scope.row.matchStatus) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="remark" label="备注"></el-table-column>
      </el-table>
      <div class="pagination-wrap">
        <el-pagination
          background
          layout="prev, pager, next"
          :total="detailTotal"
          :current-page="detailPageNum"
          :page-size="detailPageSize"
          @current-change="handleDetailPageChange">
        </el-pagination>
      </div>
    </el-dialog>

    <el-dialog title="对账差异" :visible.sync="discrepancyDialogVisible" width="1100px">
      <el-table :data="discrepancyList" border style="width: 100%">
        <el-table-column type="index" width="50"></el-table-column>
        <el-table-column prop="orderNo" label="订单号" width="200"></el-table-column>
        <el-table-column prop="channelOrderNo" label="渠道订单号" width="200"></el-table-column>
        <el-table-column label="本地金额" width="110">
          <template slot-scope="scope">
            {{ (scope.row.localAmount || 0) / 100 }} 元
          </template>
        </el-table-column>
        <el-table-column label="渠道金额" width="110">
          <template slot-scope="scope">
            {{ (scope.row.channelAmount || 0) / 100 }} 元
          </template>
        </el-table-column>
        <el-table-column prop="discrepancyType" label="差异类型" width="120"></el-table-column>
        <el-table-column label="状态" width="100">
          <template slot-scope="scope">
            <el-tag size="mini" :type="discrepancyStatusTagType(scope.row.status)">
              {{ discrepancyStatusText(scope.row.status) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="100" align="center">
          <template slot-scope="scope">
            <el-button
              v-if="scope.row.status === 'PENDING'"
              type="text"
              @click="openResolveDialog(scope.row)">处理</el-button>
          </template>
        </el-table-column>
      </el-table>
      <div class="pagination-wrap">
        <el-pagination
          background
          layout="prev, pager, next"
          :total="discrepancyTotal"
          :current-page="discrepancyPageNum"
          :page-size="discrepancyPageSize"
          @current-change="handleDiscrepancyPageChange">
        </el-pagination>
      </div>
    </el-dialog>

    <el-dialog title="处理差异" :visible.sync="resolveDialogVisible" width="500px">
      <el-form :model="resolveForm" :rules="resolveRules" ref="resolveForm" label-width="100px">
        <el-form-item label="订单号">
          <span>{{ resolveForm.orderNo }}</span>
        </el-form-item>
        <el-form-item label="差异类型">
          <span>{{ resolveForm.discrepancyType }}</span>
        </el-form-item>
        <el-form-item label="处理备注" prop="resolveRemark">
          <el-input
            v-model="resolveForm.resolveRemark"
            type="textarea"
            :rows="4"
            placeholder="请输入处理备注">
          </el-input>
        </el-form-item>
      </el-form>
      <div slot="footer">
        <el-button @click="resolveDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitResolve">确认处理</el-button>
      </div>
    </el-dialog>

    <el-dialog title="对账执行进度" :visible.sync="progressDialogVisible" width="500px">
      <div class="progress-content">
        <p>批次号：{{ currentBatchNo }}</p>
        <p>当前阶段：{{ progressInfo.stageText || '-' }}</p>
        <el-progress
          :percentage="progressInfo.percentage || 0"
          :status="progressInfo.status === 'FAILED' ? 'exception' : (progressInfo.status === 'COMPLETED' ? 'success' : '')">
        </el-progress>
        <p v-if="progressInfo.message" class="progress-msg">{{ progressInfo.message }}</p>
      </div>
      <div slot="footer">
        <el-button @click="closeProgressDialog">关闭</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
import reconciliationApi from '../api/reconciliation'

export default {
  data() {
    return {
      queryForm: {
        dateRange: [],
        channelCode: '',
        status: ''
      },
      summary: {},
      batchList: [],
      createDialogVisible: false,
      createForm: {
        channelCode: '',
        paymentAppId: '',
        billDate: ''
      },
      createRules: {
        channelCode: [{ required: true, message: '请选择渠道', trigger: 'change' }],
        paymentAppId: [{ required: true, message: '请输入支付应用ID', trigger: 'blur' }],
        billDate: [{ required: true, message: '请选择账单日期', trigger: 'change' }]
      },
      detailDialogVisible: false,
      detailList: [],
      detailTotal: 0,
      detailPageNum: 1,
      detailPageSize: 10,
      detailBatchNo: '',
      discrepancyDialogVisible: false,
      discrepancyList: [],
      discrepancyTotal: 0,
      discrepancyPageNum: 1,
      discrepancyPageSize: 10,
      discrepancyBatchNo: '',
      resolveDialogVisible: false,
      resolveForm: {
        id: null,
        orderNo: '',
        discrepancyType: '',
        resolveRemark: ''
      },
      resolveRules: {
        resolveRemark: [{ required: true, message: '请输入处理备注', trigger: 'blur' }]
      },
      progressDialogVisible: false,
      currentBatchNo: '',
      progressInfo: {},
      progressTimer: null
    }
  },

  created() {
    this.loadSummary()
    this.loadBatches()
  },

  beforeDestroy() {
    this.clearProgressTimer()
  },

  methods: {
    loadSummary() {
      reconciliationApi.getSummary().then(response => {
        this.summary = response.data || {}
      })
    },

    loadBatches() {
      const billDateStart = this.queryForm.dateRange && this.queryForm.dateRange[0] || ''
      const billDateEnd = this.queryForm.dateRange && this.queryForm.dateRange[1] || ''
      reconciliationApi.listBatches(
        this.queryForm.channelCode,
        this.queryForm.status,
        billDateStart,
        billDateEnd
      ).then(response => {
        this.batchList = response.data || []
      })
    },

    resetQuery() {
      this.queryForm.dateRange = []
      this.queryForm.channelCode = ''
      this.queryForm.status = ''
      this.loadBatches()
    },

    openCreateDialog() {
      this.createForm = {
        channelCode: '',
        paymentAppId: '',
        billDate: ''
      }
      this.createDialogVisible = true
      this.$nextTick(() => this.$refs.createForm && this.$refs.createForm.clearValidate())
    },

    submitCreate() {
      this.$refs.createForm.validate(valid => {
        if (!valid) return
        reconciliationApi.createBatch(
          this.createForm.channelCode,
          this.createForm.paymentAppId,
          this.createForm.billDate
        ).then(response => {
          this.$message.success(response.message || '创建成功')
          this.createDialogVisible = false
          this.loadSummary()
          this.loadBatches()
        })
      })
    },

    executeBatch(row) {
      this.$confirm('确认执行该对账批次？', '提示', { type: 'warning' })
        .then(() => {
          reconciliationApi.executeBatch(row.batchNo).then(response => {
            this.$message.success(response.message || '执行成功')
            this.showProgress(row)
            this.loadSummary()
            this.loadBatches()
          })
        })
        .catch(() => {})
    },

    showDetails(row) {
      this.detailBatchNo = row.batchNo
      this.detailPageNum = 1
      this.loadDetails()
      this.detailDialogVisible = true
    },

    loadDetails() {
      reconciliationApi.listDetails(
        this.detailBatchNo,
        null,
        this.detailPageNum,
        this.detailPageSize
      ).then(response => {
        const data = response.data || {}
        this.detailList = data.list || []
        this.detailTotal = data.total || 0
      })
    },

    handleDetailPageChange(page) {
      this.detailPageNum = page
      this.loadDetails()
    },

    showDiscrepancies(row) {
      this.discrepancyBatchNo = row.batchNo
      this.discrepancyPageNum = 1
      this.loadDiscrepancies()
      this.discrepancyDialogVisible = true
    },

    loadDiscrepancies() {
      reconciliationApi.listDiscrepancies(
        this.discrepancyBatchNo,
        null,
        this.discrepancyPageNum,
        this.discrepancyPageSize
      ).then(response => {
        const data = response.data || {}
        this.discrepancyList = data.list || []
        this.discrepancyTotal = data.total || 0
      })
    },

    handleDiscrepancyPageChange(page) {
      this.discrepancyPageNum = page
      this.loadDiscrepancies()
    },

    openResolveDialog(row) {
      this.resolveForm = {
        id: row.id,
        orderNo: row.orderNo,
        discrepancyType: row.discrepancyType,
        resolveRemark: ''
      }
      this.resolveDialogVisible = true
      this.$nextTick(() => this.$refs.resolveForm && this.$refs.resolveForm.clearValidate())
    },

    submitResolve() {
      this.$refs.resolveForm.validate(valid => {
        if (!valid) return
        reconciliationApi.resolveDiscrepancy(
          this.resolveForm.id,
          this.resolveForm.resolveRemark
        ).then(response => {
          this.$message.success(response.message || '处理成功')
          this.resolveDialogVisible = false
          this.loadDiscrepancies()
          this.loadBatches()
          this.loadSummary()
        })
      })
    },

    showProgress(row) {
      this.currentBatchNo = row.batchNo
      this.progressInfo = {}
      this.progressDialogVisible = true
      this.loadProgress()
      this.startProgressTimer()
    },

    loadProgress() {
      reconciliationApi.getBatchProgress(this.currentBatchNo).then(response => {
        this.progressInfo = response.data || {}
        if (this.progressInfo.status === 'COMPLETED' || this.progressInfo.status === 'FAILED') {
          this.clearProgressTimer()
          this.loadBatches()
          this.loadSummary()
        }
      })
    },

    startProgressTimer() {
      this.clearProgressTimer()
      this.progressTimer = setInterval(() => {
        this.loadProgress()
      }, 3000)
    },

    clearProgressTimer() {
      if (this.progressTimer) {
        clearInterval(this.progressTimer)
        this.progressTimer = null
      }
    },

    closeProgressDialog() {
      this.progressDialogVisible = false
      this.clearProgressTimer()
    },

    channelText(code) {
      const map = { WXPAY: '微信支付', ALIPAY: '支付宝' }
      return map[code] || code || '-'
    },

    batchStatusText(status) {
      const map = {
        PENDING: '待处理',
        PROCESSING: '处理中',
        COMPLETED: '已完成',
        FAILED: '失败'
      }
      return map[status] || status || '-'
    },

    batchStatusTagType(status) {
      const map = {
        PENDING: 'info',
        PROCESSING: 'warning',
        COMPLETED: 'success',
        FAILED: 'danger'
      }
      return map[status] || ''
    },

    matchStatusText(status) {
      const map = {
        MATCHED: '已匹配',
        MISMATCHED: '不匹配',
        LOCAL_ONLY: '仅本地',
        CHANNEL_ONLY: '仅渠道'
      }
      return map[status] || status || '-'
    },

    matchStatusTagType(status) {
      const map = {
        MATCHED: 'success',
        MISMATCHED: 'warning',
        LOCAL_ONLY: 'danger',
        CHANNEL_ONLY: 'danger'
      }
      return map[status] || ''
    },

    discrepancyStatusText(status) {
      const map = {
        PENDING: '待处理',
        RESOLVED: '已处理'
      }
      return map[status] || status || '-'
    },

    discrepancyStatusTagType(status) {
      const map = {
        PENDING: 'warning',
        RESOLVED: 'success'
      }
      return map[status] || ''
    }
  }
}
</script>

<style scoped>
.filter-form {
  background: #fff;
  padding: 16px;
  border-radius: 4px;
  margin-bottom: 16px;
}
.summary-row {
  margin-bottom: 16px;
}
.summary-row .el-card {
  text-align: center;
}
.pagination-wrap {
  margin-top: 16px;
  text-align: right;
}
.progress-content p {
  margin: 8px 0;
}
.progress-msg {
  color: #909399;
  font-size: 13px;
}
</style>

// springboot-payment/payment-demo-java-dm/payment-demo-react/src/pages/Reconciliation.jsx
import { useCallback, useEffect, useState } from 'react'
import {
  Button,
  Card,
  Col,
  DatePicker,
  Form,
  Input,
  message,
  Modal,
  Progress,
  Row,
  Select,
  Space,
  Statistic,
  Table,
  Tag
} from 'antd'
import dayjs from 'dayjs'
import {
  createBatch,
  executeBatch,
  getBatchDetail,
  getBatchList,
  getDetailList,
  getDiscrepancyList,
  getProgress,
  getSummary,
  resolveDiscrepancy
} from '@/api/reconciliation'

const { RangePicker } = DatePicker
const { TextArea } = Input

const CHANNEL_OPTIONS = [
  { label: '全部', value: '' },
  { label: '微信支付', value: 'WXPAY' },
  { label: '支付宝', value: 'ALIPAY' }
]

const STATUS_OPTIONS = [
  { label: '全部', value: '' },
  { label: '待执行', value: 'PENDING' },
  { label: '执行中', value: 'EXECUTING' },
  { label: '已完成', value: 'COMPLETED' },
  { label: '失败', value: 'FAILED' }
]

const statusColorMap = {
  PENDING: 'default',
  EXECUTING: 'processing',
  COMPLETED: 'success',
  FAILED: 'error'
}

const statusTextMap = {
  PENDING: '待执行',
  EXECUTING: '执行中',
  COMPLETED: '已完成',
  FAILED: '失败'
}

const channelTextMap = {
  WXPAY: '微信支付',
  ALIPAY: '支付宝'
}

const matchStatusMap = {
  MATCHED: { text: '匹配', color: 'success' },
  MISMATCH: { text: '不匹配', color: 'error' },
  MISSING_LOCAL: { text: '本地缺失', color: 'warning' },
  MISSING_CHANNEL: { text: '渠道缺失', color: 'orange' }
}

const discrepancyTypeMap = {
  AMOUNT_MISMATCH: { text: '金额不一致', color: 'red' },
  STATUS_MISMATCH: { text: '状态不一致', color: 'orange' },
  MISSING_LOCAL: { text: '本地缺失', color: 'gold' },
  MISSING_CHANNEL: { text: '渠道缺失', color: 'purple' }
}

const discrepancyStatusMap = {
  PENDING: { text: '待处理', color: 'processing' },
  RESOLVED: { text: '已处理', color: 'success' },
  IGNORED: { text: '已忽略', color: 'default' }
}

export default function Reconciliation() {
  const [queryForm] = Form.useForm()
  const [createForm] = Form.useForm()
  const [resolveForm] = Form.useForm()

  const [summary, setSummary] = useState({})
  const [batchList, setBatchList] = useState([])
  const [batchTotal, setBatchTotal] = useState(0)
  const [batchPageNum, setBatchPageNum] = useState(1)
  const [batchPageSize, setBatchPageSize] = useState(10)
  const [loading, setLoading] = useState(false)

  const [createDialogVisible, setCreateDialogVisible] = useState(false)
  const [detailDialogVisible, setDetailDialogVisible] = useState(false)
  const [discrepancyDialogVisible, setDiscrepancyDialogVisible] = useState(false)
  const [progressDialogVisible, setProgressDialogVisible] = useState(false)
  const [resolveDialogVisible, setResolveDialogVisible] = useState(false)

  const [currentBatch, setCurrentBatch] = useState(null)
  const [currentDiscrepancy, setCurrentDiscrepancy] = useState(null)

  const [detailList, setDetailList] = useState([])
  const [detailTotal, setDetailTotal] = useState(0)
  const [detailPageNum, setDetailPageNum] = useState(1)
  const [detailPageSize, setDetailPageSize] = useState(10)
  const [detailLoading, setDetailLoading] = useState(false)
  const [detailFilters, setDetailFilters] = useState({ matchStatus: '', tradeType: '' })

  const [discrepancyList, setDiscrepancyList] = useState([])
  const [discrepancyTotal, setDiscrepancyTotal] = useState(0)
  const [discrepancyPageNum, setDiscrepancyPageNum] = useState(1)
  const [discrepancyPageSize, setDiscrepancyPageSize] = useState(10)
  const [discrepancyLoading, setDiscrepancyLoading] = useState(false)
  const [discrepancyFilters, setDiscrepancyFilters] = useState({ status: '', discrepancyType: '' })

  const [progressInfo, setProgressInfo] = useState(null)
  const [progressTimer, setProgressTimer] = useState(null)

  const loadSummary = useCallback(() => {
    getSummary().then((res) => {
      setSummary(res?.data || {})
    })
  }, [])

  const loadBatchList = useCallback(() => {
    setLoading(true)
    const values = queryForm.getFieldsValue()
    const params = {
      pageNum: batchPageNum,
      pageSize: batchPageSize
    }
    if (values.dateRange && values.dateRange.length === 2) {
      params.startDate = values.dateRange[0].format('YYYY-MM-DD')
      params.endDate = values.dateRange[1].format('YYYY-MM-DD')
    }
    if (values.channelCode) {
      params.channelCode = values.channelCode
    }
    if (values.status) {
      params.status = values.status
    }
    getBatchList(params)
      .then((res) => {
        setBatchList(res?.data?.list || [])
        setBatchTotal(res?.data?.total || 0)
      })
      .finally(() => {
        setLoading(false)
      })
  }, [batchPageNum, batchPageSize, queryForm])

  useEffect(() => {
    loadSummary()
    loadBatchList()
  }, [loadSummary, loadBatchList])

  const handleQuery = () => {
    setBatchPageNum(1)
    setTimeout(() => loadBatchList(), 0)
  }

  const handleReset = () => {
    queryForm.resetFields()
    setBatchPageNum(1)
    setTimeout(() => loadBatchList(), 0)
  }

  const openCreateDialog = () => {
    createForm.resetFields()
    setCreateDialogVisible(true)
  }

  const handleCreateBatch = () => {
    createForm.validateFields().then((values) => {
      const data = {
        channelCode: values.channelCode,
        billDate: values.billDate.format('YYYY-MM-DD')
      }
      createBatch(data).then((res) => {
        message.success(res.message || '批次创建成功')
        setCreateDialogVisible(false)
        loadSummary()
        loadBatchList()
      })
    })
  }

  const handleExecute = (row) => {
    Modal.confirm({
      title: '确认执行对账',
      content: `确定要执行批次 ${row.batchNo} 的对账任务吗？`,
      onOk: () => {
        executeBatch(row.batchNo).then((res) => {
          message.success(res.message || '对账任务已启动')
          loadBatchList()
        })
      }
    })
  }

  const openDetailDialog = (row) => {
    setCurrentBatch(row)
    setDetailPageNum(1)
    setDetailFilters({ matchStatus: '', tradeType: '' })
    setDetailDialogVisible(true)
  }

  const loadDetailList = useCallback(() => {
    if (!currentBatch) return
    setDetailLoading(true)
    const params = {
      pageNum: detailPageNum,
      pageSize: detailPageSize,
      ...detailFilters
    }
    getDetailList(currentBatch.batchNo, params)
      .then((res) => {
        setDetailList(res?.data?.list || [])
        setDetailTotal(res?.data?.total || 0)
      })
      .finally(() => {
        setDetailLoading(false)
      })
  }, [currentBatch, detailPageNum, detailPageSize, detailFilters])

  useEffect(() => {
    if (detailDialogVisible && currentBatch) {
      loadDetailList()
    }
  }, [detailDialogVisible, currentBatch, loadDetailList])

  const openDiscrepancyDialog = (row) => {
    setCurrentBatch(row)
    setDiscrepancyPageNum(1)
    setDiscrepancyFilters({ status: '', discrepancyType: '' })
    setDiscrepancyDialogVisible(true)
  }

  const loadDiscrepancyList = useCallback(() => {
    if (!currentBatch) return
    setDiscrepancyLoading(true)
    const params = {
      pageNum: discrepancyPageNum,
      pageSize: discrepancyPageSize,
      ...discrepancyFilters
    }
    getDiscrepancyList(currentBatch.batchNo, params)
      .then((res) => {
        setDiscrepancyList(res?.data?.list || [])
        setDiscrepancyTotal(res?.data?.total || 0)
      })
      .finally(() => {
        setDiscrepancyLoading(false)
      })
  }, [currentBatch, discrepancyPageNum, discrepancyPageSize, discrepancyFilters])

  useEffect(() => {
    if (discrepancyDialogVisible && currentBatch) {
      loadDiscrepancyList()
    }
  }, [discrepancyDialogVisible, currentBatch, loadDiscrepancyList])

  const openResolveDialog = (row) => {
    setCurrentDiscrepancy(row)
    resolveForm.resetFields()
    setResolveDialogVisible(true)
  }

  const handleResolve = () => {
    resolveForm.validateFields().then((values) => {
      resolveDiscrepancy(currentDiscrepancy.id, { resolveRemark: values.resolveRemark }).then((res) => {
        message.success(res.message || '处理成功')
        setResolveDialogVisible(false)
        loadDiscrepancyList()
        loadSummary()
        loadBatchList()
      })
    })
  }

  const openProgressDialog = (row) => {
    setCurrentBatch(row)
    setProgressInfo(null)
    setProgressDialogVisible(true)
  }

  const loadProgress = useCallback(() => {
    if (!currentBatch) return
    getProgress(currentBatch.batchNo).then((res) => {
      setProgressInfo(res?.data || null)
      if (res?.data?.status === 'COMPLETED' || res?.data?.status === 'FAILED') {
        if (progressTimer) {
          clearInterval(progressTimer)
          setProgressTimer(null)
        }
      }
    })
  }, [currentBatch, progressTimer])

  useEffect(() => {
    if (progressDialogVisible && currentBatch) {
      loadProgress()
      const timer = setInterval(() => {
        loadProgress()
      }, 2000)
      setProgressTimer(timer)
      return () => {
        if (timer) clearInterval(timer)
      }
    } else {
      if (progressTimer) {
        clearInterval(progressTimer)
        setProgressTimer(null)
      }
    }
  }, [progressDialogVisible, currentBatch, loadProgress])

  const batchColumns = [
    { title: '#', width: 50, render: (_, __, index) => (batchPageNum - 1) * batchPageSize + index + 1 },
    { title: '批次号', dataIndex: 'batchNo', width: 200 },
    {
      title: '渠道',
      dataIndex: 'channelCode',
      width: 100,
      render: (code) => channelTextMap[code] || code
    },
    { title: '账单日期', dataIndex: 'billDate', width: 110 },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (status) => (
        <Tag color={statusColorMap[status] || 'default'}>{statusTextMap[status] || status}</Tag>
      )
    },
    { title: '渠道笔数', dataIndex: 'channelCount', width: 100 },
    { title: '本地笔数', dataIndex: 'localCount', width: 100 },
    { title: '匹配笔数', dataIndex: 'matchedCount', width: 100 },
    { title: '差异笔数', dataIndex: 'discrepancyCount', width: 100 },
    {
      title: '操作',
      width: 280,
      align: 'center',
      fixed: 'right',
      render: (_, row) => (
        <Space size="small" wrap>
          {row.status !== 'COMPLETED' && (
            <Button type="link" onClick={() => handleExecute(row)}>
              执行
            </Button>
          )}
          <Button type="link" onClick={() => openDetailDialog(row)}>
            查看明细
          </Button>
          <Button type="link" onClick={() => openDiscrepancyDialog(row)}>
            查看差异
          </Button>
          <Button type="link" onClick={() => openProgressDialog(row)}>
            进度
          </Button>
        </Space>
      )
    }
  ]

  const detailColumns = [
    { title: '#', width: 50, render: (_, __, index) => (detailPageNum - 1) * detailPageSize + index + 1 },
    { title: '订单号', dataIndex: 'orderNo', width: 200 },
    { title: '交易类型', dataIndex: 'tradeType', width: 100 },
    {
      title: '匹配状态',
      dataIndex: 'matchStatus',
      width: 110,
      render: (status) => (
        <Tag color={matchStatusMap[status]?.color || 'default'}>{matchStatusMap[status]?.text || status}</Tag>
      )
    },
    { title: '渠道金额', dataIndex: 'channelAmount', width: 110 },
    { title: '本地金额', dataIndex: 'localAmount', width: 110 },
    { title: '渠道时间', dataIndex: 'channelTime', width: 170 },
    { title: '本地时间', dataIndex: 'localTime', width: 170 }
  ]

  const discrepancyColumns = [
    { title: '#', width: 50, render: (_, __, index) => (discrepancyPageNum - 1) * discrepancyPageSize + index + 1 },
    { title: '订单号', dataIndex: 'orderNo', width: 200 },
    {
      title: '差异类型',
      dataIndex: 'discrepancyType',
      width: 130,
      render: (type) => (
        <Tag color={discrepancyTypeMap[type]?.color || 'default'}>
          {discrepancyTypeMap[type]?.text || type}
        </Tag>
      )
    },
    { title: '渠道金额', dataIndex: 'channelAmount', width: 110 },
    { title: '本地金额', dataIndex: 'localAmount', width: 110 },
    {
      title: '处理状态',
      dataIndex: 'status',
      width: 100,
      render: (status) => (
        <Tag color={discrepancyStatusMap[status]?.color || 'default'}>
          {discrepancyStatusMap[status]?.text || status}
        </Tag>
      )
    },
    { title: '处理备注', dataIndex: 'resolveRemark' },
    {
      title: '操作',
      width: 100,
      align: 'center',
      fixed: 'right',
      render: (_, row) =>
        row.status === 'PENDING' ? (
          <Button type="link" onClick={() => openResolveDialog(row)}>
            处理
          </Button>
        ) : null
    }
  ]

  return (
    <div className="bg-fa of">
      <section id="index" className="container">
        <header className="comm-title">
          <h2>对账管理</h2>
        </header>

        <Card style={{ marginBottom: 16 }}>
          <Form form={queryForm} layout="inline">
            <Form.Item label="账单日期" name="dateRange">
              <RangePicker />
            </Form.Item>
            <Form.Item label="渠道" name="channelCode">
              <Select style={{ width: 140 }} options={CHANNEL_OPTIONS} />
            </Form.Item>
            <Form.Item label="状态" name="status">
              <Select style={{ width: 140 }} options={STATUS_OPTIONS} />
            </Form.Item>
            <Form.Item>
              <Space>
                <Button type="primary" onClick={handleQuery}>
                  查询
                </Button>
                <Button onClick={handleReset}>重置</Button>
                <Button type="primary" onClick={openCreateDialog}>
                  手动对账
                </Button>
              </Space>
            </Form.Item>
          </Form>
        </Card>

        <Row gutter={16} style={{ marginBottom: 16 }}>
          <Col span={6}>
            <Card>
              <Statistic title="今日批次" value={summary.todayBatchCount || 0} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic
                title="完成数"
                value={summary.todayCompletedCount || 0}
                valueStyle={{ color: '#3f8600' }}
              />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic
                title="失败数"
                value={summary.todayFailedCount || 0}
                valueStyle={{ color: '#cf1322' }}
              />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic
                title="待处理差异"
                value={summary.pendingDiscrepancyCount || 0}
                valueStyle={{ color: '#fa8c16' }}
              />
            </Card>
          </Col>
        </Row>

        <Card>
          <Table
            rowKey="id"
            dataSource={batchList}
            columns={batchColumns}
            bordered
            loading={loading}
            scroll={{ x: 1300 }}
            pagination={{
              current: batchPageNum,
              pageSize: batchPageSize,
              total: batchTotal,
              showSizeChanger: true,
              showQuickJumper: true,
              showTotal: (total) => `共 ${total} 条`,
              onChange: (page, pageSize) => {
                setBatchPageNum(page)
                setBatchPageSize(pageSize)
              }
            }}
          />
        </Card>
      </section>

      <Modal
        title="创建对账批次"
        open={createDialogVisible}
        width={500}
        onCancel={() => setCreateDialogVisible(false)}
        onOk={handleCreateBatch}
        okText="创建"
        cancelText="取消"
      >
        <Form form={createForm} layout="vertical">
          <Form.Item label="支付渠道" name="channelCode" rules={[{ required: true, message: '请选择支付渠道' }]}>
            <Select placeholder="请选择支付渠道">
              <Select.Option value="WXPAY">微信支付</Select.Option>
              <Select.Option value="ALIPAY">支付宝</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item label="账单日期" name="billDate" rules={[{ required: true, message: '请选择账单日期' }]}>
            <DatePicker style={{ width: '100%' }} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="对账明细"
        open={detailDialogVisible}
        width={1100}
        onCancel={() => setDetailDialogVisible(false)}
        footer={null}
      >
        <Space style={{ marginBottom: 16 }}>
          <Select
            placeholder="匹配状态"
            style={{ width: 140 }}
            allowClear
            value={detailFilters.matchStatus || undefined}
            onChange={(val) => {
              setDetailFilters({ ...detailFilters, matchStatus: val || '' })
              setDetailPageNum(1)
            }}
          >
            <Select.Option value="MATCHED">匹配</Select.Option>
            <Select.Option value="MISMATCH">不匹配</Select.Option>
            <Select.Option value="MISSING_LOCAL">本地缺失</Select.Option>
            <Select.Option value="MISSING_CHANNEL">渠道缺失</Select.Option>
          </Select>
        </Space>
        <Table
          rowKey="id"
          dataSource={detailList}
          columns={detailColumns}
          bordered
          loading={detailLoading}
          scroll={{ x: 1000 }}
          pagination={{
            current: detailPageNum,
            pageSize: detailPageSize,
            total: detailTotal,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共 ${total} 条`,
            onChange: (page, pageSize) => {
              setDetailPageNum(page)
              setDetailPageSize(pageSize)
            }
          }}
        />
      </Modal>

      <Modal
        title="差异列表"
        open={discrepancyDialogVisible}
        width={1100}
        onCancel={() => setDiscrepancyDialogVisible(false)}
        footer={null}
      >
        <Space style={{ marginBottom: 16 }}>
          <Select
            placeholder="处理状态"
            style={{ width: 140 }}
            allowClear
            value={discrepancyFilters.status || undefined}
            onChange={(val) => {
              setDiscrepancyFilters({ ...discrepancyFilters, status: val || '' })
              setDiscrepancyPageNum(1)
            }}
          >
            <Select.Option value="PENDING">待处理</Select.Option>
            <Select.Option value="RESOLVED">已处理</Select.Option>
            <Select.Option value="IGNORED">已忽略</Select.Option>
          </Select>
          <Select
            placeholder="差异类型"
            style={{ width: 160 }}
            allowClear
            value={discrepancyFilters.discrepancyType || undefined}
            onChange={(val) => {
              setDiscrepancyFilters({ ...discrepancyFilters, discrepancyType: val || '' })
              setDiscrepancyPageNum(1)
            }}
          >
            <Select.Option value="AMOUNT_MISMATCH">金额不一致</Select.Option>
            <Select.Option value="STATUS_MISMATCH">状态不一致</Select.Option>
            <Select.Option value="MISSING_LOCAL">本地缺失</Select.Option>
            <Select.Option value="MISSING_CHANNEL">渠道缺失</Select.Option>
          </Select>
        </Space>
        <Table
          rowKey="id"
          dataSource={discrepancyList}
          columns={discrepancyColumns}
          bordered
          loading={discrepancyLoading}
          scroll={{ x: 1100 }}
          pagination={{
            current: discrepancyPageNum,
            pageSize: discrepancyPageSize,
            total: discrepancyTotal,
            showSizeChanger: true,
            showQuickJumper: true,
            showTotal: (total) => `共 ${total} 条`,
            onChange: (page, pageSize) => {
              setDiscrepancyPageNum(page)
              setDiscrepancyPageSize(pageSize)
            }
          }}
        />
      </Modal>

      <Modal
        title="处理差异"
        open={resolveDialogVisible}
        width={500}
        onCancel={() => setResolveDialogVisible(false)}
        onOk={handleResolve}
        okText="确认处理"
        cancelText="取消"
      >
        <Form form={resolveForm} layout="vertical">
          <Form.Item label="处理备注" name="resolveRemark" rules={[{ required: true, message: '请输入处理备注' }]}>
            <TextArea rows={4} placeholder="请输入差异处理说明" />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="执行进度"
        open={progressDialogVisible}
        width={500}
        onCancel={() => setProgressDialogVisible(false)}
        footer={[
          <Button key="close" onClick={() => setProgressDialogVisible(false)}>
            关闭
          </Button>
        ]}
      >
        {progressInfo ? (
          <div>
            <p>
              批次号：<strong>{progressInfo.batchNo}</strong>
            </p>
            <p>
              状态：
              <Tag color={statusColorMap[progressInfo.status] || 'default'}>
                {statusTextMap[progressInfo.status] || progressInfo.status}
              </Tag>
            </p>
            <p>
              总笔数：{progressInfo.totalCount || 0}
            </p>
            <p>
              已处理：{progressInfo.processedCount || 0}
            </p>
            <Progress
              percent={progressInfo.totalCount ? Math.round((progressInfo.processedCount / progressInfo.totalCount) * 100) : 0}
              status={progressInfo.status === 'FAILED' ? 'exception' : progressInfo.status === 'COMPLETED' ? 'success' : 'active'}
            />
            {progressInfo.errorMessage && (
              <p style={{ color: '#cf1322', marginTop: 12 }}>错误信息：{progressInfo.errorMessage}</p>
            )}
          </div>
        ) : (
          <p>加载中...</p>
        )}
      </Modal>
    </div>
  )
}
