// springboot-payment-v1/payment-demo-v5/payment-demo-vue/src/components/AppHeader.vue
<template>
  <!-- 公共头 -->
  <header id="header">
    <section class="container">
      <h1 id="logo">
        <a href="#/" title="谷粒学院">
          <img src="../assets/img/logo.png" width="100%" alt="谷粒学院">
        </a>
      </h1>
      <div>
        <ul class="nav">
          <router-link to="/" tag="li" active-class="current" exact>
            <a>购买课程</a>
          </router-link>
          <router-link to="/orders" tag="li" active-class="current">
            <a>我的订单</a>
          </router-link>
          <router-link to="/download" tag="li" active-class="current">
            <a>下载账单</a>
          </router-link>
          <router-link to="/payment-config" tag="li" active-class="current">
            <a>支付配置</a>
          </router-link>
        </ul>
      </div>
      <div class="clear"></div>
    </section>
  </header>
</template>

// springboot-payment-v1/payment-demo-v5/payment-demo-react/src/components/AppHeader.jsx
import { Link, NavLink, useLocation } from 'react-router-dom'
import logo from '@/assets/img/logo.png'

export default function AppHeader() {
  const location = useLocation()

  const liClassName = (path, exact = false) => {
    if (exact) {
      return location.pathname === path ? 'current' : ''
    }
    return location.pathname.startsWith(path) ? 'current' : ''
  }

  return (
    <header id="header">
      <section className="container">
        <h1 id="logo">
          <Link to="/" title="谷粒学院">
            <img src={logo} width="100%" alt="谷粒学院" />
          </Link>
        </h1>
        <div>
          <ul className="nav">
            <li className={liClassName('/', true)}>
              <NavLink to="/" end>购买课程</NavLink>
            </li>
            <li className={liClassName('/orders')}>
              <NavLink to="/orders">我的订单</NavLink>
            </li>
            <li className={liClassName('/download')}>
              <NavLink to="/download">下载账单</NavLink>
            </li>
            <li className={liClassName('/payment-config')}>
              <NavLink to="/payment-config">支付配置</NavLink>
            </li>
          </ul>
        </div>
        <div className="clear" />
      </section>
    </header>
  )
}
