// springboot-payment/payment-demo-java/payment-demo-vue/src/views/Account.vue
<template>
  <main class="container page-shell narrow-page">
    <header class="page-heading">
      <h1>账号安全</h1>
      <p>修改密码后，所有设备上的刷新会话都会失效。</p>
    </header>
    <section class="surface account-panel">
      <div class="account-name">
        <span>当前账号</span>
        <strong>{{ auth.user && auth.user.username }}</strong>
        <small>{{ auth.user && auth.user.role }}</small>
      </div>
      <el-form ref="form" :model="form" :rules="rules" label-position="top">
        <el-form-item label="原密码" prop="oldPassword">
          <el-input v-model="form.oldPassword" type="password" show-password autocomplete="current-password" />
        </el-form-item>
        <el-form-item label="新密码" prop="newPassword">
          <el-input v-model="form.newPassword" type="password" show-password autocomplete="new-password" />
        </el-form-item>
        <el-button type="primary" @click="submit">修改密码</el-button>
      </el-form>
    </section>
  </main>
</template>

<script>
import authApi from '../api/auth'
import { authState, clearSession } from '../auth/session'

export default {
  data() {
    return {
      auth: authState,
      form: { oldPassword: '', newPassword: '' },
      rules: {
        oldPassword: [{ required: true, message: '请输入原密码', trigger: 'blur' }],
        newPassword: [
          { required: true, message: '请输入新密码', trigger: 'blur' },
          { min: 8, message: '密码至少 8 位', trigger: 'blur' }
        ]
      }
    }
  },
  methods: {
    submit() {
      this.$refs.form.validate(async valid => {
        if (!valid) return
        await authApi.changePassword(this.form)
        try {
          await authApi.logout()
        } finally {
          clearSession()
          this.$message.success('密码已修改，请重新登录')
          this.$router.replace('/login')
        }
      })
    }
  }
}
</script>

// springboot-payment/payment-demo-java/payment-demo-react/src/pages/Account.jsx
import { Button, Form, Input, message } from 'antd'
import { useNavigate } from 'react-router-dom'

import authApi from '@/api/auth'
import { useAuth } from '@/auth/AuthContext'

export default function Account() {
  const auth = useAuth()
  const navigate = useNavigate()

  const submit = async (values) => {
    await authApi.changePassword(values)
    message.success('密码已修改，请重新登录')
    await auth.logout()
    navigate('/login', { replace: true })
  }

  return (
    <main className="container page-shell narrow-page">
      <header className="page-heading">
        <h1>账号安全</h1>
        <p>修改密码后，所有设备上的刷新会话都会失效。</p>
      </header>
      <section className="surface account-panel">
        <div className="account-name">
          <span>当前账号</span>
          <strong>{auth.user?.username}</strong>
          <small>{auth.user?.role}</small>
        </div>
        <Form layout="vertical" requiredMark={false} onFinish={submit}>
          <Form.Item label="原密码" name="oldPassword" rules={[{ required: true, message: '请输入原密码' }]}>
            <Input.Password autoComplete="current-password" />
          </Form.Item>
          <Form.Item label="新密码" name="newPassword" rules={[{ required: true, message: '请输入新密码' }, { min: 8, message: '密码至少 8 位' }]}>
            <Input.Password autoComplete="new-password" />
          </Form.Item>
          <Button type="primary" htmlType="submit">修改密码</Button>
        </Form>
      </section>
    </main>
  )
}
