// springboot-payment/payment-demo-java/payment-demo-vue/src/views/Orders.vue
<template>
  <div class="bg-fa of">
    <section id="index" class="container">
      <header class="comm-title">
        <h2>{{ isAdmin ? '全部订单' : '我的订单' }}</h2>
      </header>
      <el-table :data="list" v-loading="loading" border style="width: 100%" @expand-change="loadItems">
        <el-table-column type="expand">
          <template slot-scope="scope">
            <div v-if="itemsByOrder[scope.row.orderNo] && itemsByOrder[scope.row.orderNo].length" class="order-items">
              <div v-for="item in itemsByOrder[scope.row.orderNo]" :key="item.id || item.productId">
                <span>{{ item.productTitle }}</span>
                <span>¥{{ (item.unitPrice / 100).toFixed(2) }} × {{ item.quantity }}</span>
                <strong>¥{{ (item.subtotal / 100).toFixed(2) }}</strong>
              </div>
            </div>
            <span v-else>正在读取订单明细...</span>
          </template>
        </el-table-column>
        <el-table-column type="index" width="50"></el-table-column>
        <el-table-column prop="orderNo" label="订单编号" width="230"></el-table-column>
        <el-table-column prop="title" label="订单标题"></el-table-column>
        <el-table-column prop="totalFee" label="订单金额">
          <template slot-scope="scope">
            {{ scope.row.totalFee / 100 }} 元
          </template>
        </el-table-column>
        <el-table-column prop="paymentType" label="支付方式"></el-table-column>
        <el-table-column label="订单状态">
          <template slot-scope="scope">
            <el-tag v-if="scope.row.orderStatus === '未支付'">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '支付成功'" type="success">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '部分退款'" type="warning">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '超时已关闭'" type="warning">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '用户已取消'" type="info">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '退款中'" type="danger">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '已退款'" type="info">{{ scope.row.orderStatus }}</el-tag>
            <el-tag v-if="scope.row.orderStatus === '退款异常'" type="danger">{{ scope.row.orderStatus }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" :width="isAdmin ? 300 : 340" align="center">
          <template slot-scope="scope">
            <template v-if="isAdmin">
              <el-button type="text" :loading="checkingPaymentOrderNo === scope.row.orderNo" @click="checkPaymentStatus(scope.row)">查询支付状态</el-button>
              <el-button type="text" :loading="reconcilingOrderNo === scope.row.orderNo" @click="reconcileRefunds(scope.row)">对账退款</el-button>
              <el-button type="text" @click="showRefundRecords(scope.row)">退款记录</el-button>
            </template>
            <template v-else>
              <template v-if="scope.row.orderStatus === '未支付'">
                <el-button type="text" :loading="payingOrderNo === scope.row.orderNo" @click="retryPay(scope.row)">重试支付</el-button>
                <el-button v-if="scope.row.paymentChannelCode === 'WXPAY' || scope.row.paymentType === '微信'" type="text" @click="retryPay(scope.row, 'V2')">微信 V2</el-button>
                <el-button type="text" @click="cancel(scope.row.orderNo, scope.row.paymentType)">取消</el-button>
              </template>
              <el-button v-if="canApplyRefund(scope.row.orderStatus)" type="text" @click="refund(scope.row)">退款申请</el-button>
              <el-button type="text" @click="showRefundRecords(scope.row)">退款申请记录</el-button>
            </template>
          </template>
        </el-table-column>
      </el-table>
    </section>

    <el-dialog
      :visible.sync="refundDialogVisible"
      @close="closeDialog"
      width="420px"
      center>
      <el-form label-width="100px">
        <el-form-item label="订单编号">
          <span>{{ orderNo }}</span>
        </el-form-item>
        <el-form-item label="订单金额">
          <span>{{ currentOrderTotalFee / 100 }} 元</span>
        </el-form-item>
        <el-form-item label="退款金额">
          <el-input-number
            v-model="refundAmountYuan"
            :precision="2"
            :step="0.01"
            :min="0.01"
            :max="currentOrderTotalFee / 100"
            controls-position="right"
            style="width: 100%">
          </el-input-number>
        </el-form-item>
        <el-form-item label="退款原因">
          <el-select v-model="reason" placeholder="请选择退款原因" style="width: 100%">
            <el-option label="不喜欢" value="不喜欢"></el-option>
            <el-option label="买错了" value="买错了"></el-option>
            <el-option label="其他" value="其他"></el-option>
          </el-select>
        </el-form-item>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="closeDialog">取 消</el-button>
        <el-button type="primary" @click="toRefunds()" :disabled="refundSubmitBtnDisabled">确 定</el-button>
      </div>
    </el-dialog>

    <el-dialog
      title="退款申请记录"
      :visible.sync="refundRecordDialogVisible"
      width="900px"
      center>
      <el-table :data="refundRecordList" border style="width: 100%">
        <el-table-column prop="refundNo" label="退款申请单号" width="210"></el-table-column>
        <el-table-column label="退款金额" width="110">
          <template slot-scope="scope">
            {{ (scope.row.refund || 0) / 100 }} 元
          </template>
        </el-table-column>
        <el-table-column label="审核状态" width="110">
          <template slot-scope="scope">
            <el-tag size="mini" :type="approvalTagType(scope.row.approvalStatus)">
              {{ approvalStatusText(scope.row.approvalStatus) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="退款状态" width="110">
          <template slot-scope="scope">
            <el-tag size="mini" :type="refundTagType(scope.row.refundStatus)">
              {{ refundStatusText(scope.row.refundStatus) }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="reason" label="退款原因"></el-table-column>
        <el-table-column prop="approveRemark" label="审核备注"></el-table-column>
        <el-table-column prop="createTime" label="申请时间" width="170"></el-table-column>
      </el-table>
    </el-dialog>

    <el-dialog :visible.sync="payDialog.open" width="360px" center @close="closePayDialog">
      <div class="wxpay-dialog">
        <h3>微信扫码支付</h3>
        <p>支付完成后，订单状态会自动更新。</p>
        <qriously v-if="payDialog.codeUrl" :value="payDialog.codeUrl" :size="280" />
        <el-button @click="closePayDialog">稍后支付</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
import aliPay from '../api/aliPay'
import orderInfoApi from '../api/orderInfo'
import wxPayApi from '../api/wxPay'
import refundInfoApi from '../api/refundInfo'
import { authState } from '../auth/session'

export default {
  data() {
    return {
      list: [],
      loading: true,
      auth: authState,
      itemsByOrder: {},
      payingOrderNo: '',
      payDialog: { open: false, codeUrl: '', orderNo: '' },
      timer: null,
      refundDialogVisible: false,
      refundRecordDialogVisible: false,
      refundRecordList: [],
      orderNo: '',
      reason: '',
      refundAmountYuan: 0.01,
      currentOrderTotalFee: 0,
      refundSubmitBtnDisabled: false,
      paymentType: '',
      checkingPaymentOrderNo: '',
      reconcilingOrderNo: ''
    }
  },

  created() {
    this.showOrderList()
  },

  beforeDestroy() {
    clearInterval(this.timer)
  },

  computed: {
    isAdmin() {
      return this.auth.user && this.auth.user.role === 'ADMIN'
    }
  },

  methods: {
    showOrderList() {
      this.loading = true
      const request = this.isAdmin ? orderInfoApi.list() : orderInfoApi.myList()
      request.then((response) => {
        this.list = response.data.list
      }).finally(() => {
        this.loading = false
      })
    },

    loadItems(row, expandedRows) {
      if (!expandedRows.length || this.itemsByOrder[row.orderNo]) return
      orderInfoApi.items(row.orderNo).then(response => {
        this.$set(this.itemsByOrder, row.orderNo, response.data || [])
      })
    },

    openWxPay(response, orderNo) {
      this.payDialog = { open: true, codeUrl: (response.data && response.data.codeUrl) || '', orderNo }
      clearInterval(this.timer)
      this.timer = setInterval(async () => {
        const status = await orderInfoApi.queryOrderStatus(orderNo)
        if (status.code === 0) {
          clearInterval(this.timer)
          this.payDialog.open = false
          this.$message.success('支付成功')
          this.showOrderList()
        }
      }, 3000)
    },

    async retryPay(row, wxVersion) {
      this.payingOrderNo = row.orderNo
      try {
        const channelCode = row.paymentChannelCode || (row.paymentType === '支付宝' ? 'ALIPAY' : 'WXPAY')
        if (channelCode === 'WXPAY') {
          const response = wxVersion === 'V2'
            ? await wxPayApi.nativePayV2Order(row.orderNo)
            : await wxPayApi.nativePayOrder(row.orderNo)
          this.openWxPay(response, row.orderNo)
        } else if (channelCode === 'ALIPAY') {
          const response = await aliPay.tradePagePayOrder(row.orderNo)
          document.open()
          document.write((response.data && response.data.formStr) || '')
          document.close()
        } else {
          this.$message.error('暂不支持该订单的支付渠道')
        }
      } finally {
        this.payingOrderNo = ''
      }
    },

    closePayDialog() {
      clearInterval(this.timer)
      this.payDialog = { open: false, codeUrl: '', orderNo: '' }
      this.showOrderList()
    },

    canApplyRefund(orderStatus) {
      return orderStatus === '支付成功' || orderStatus === '部分退款' || orderStatus === '退款中'
    },

    cancel(orderNo, paymentType) {
      if (paymentType === '微信') {
        wxPayApi.cancel(orderNo).then((response) => {
          this.$message.success(response.message)
          this.showOrderList()
        })
      } else {
        aliPay.cancel(orderNo).then((response) => {
          this.$message.success(response.message)
          this.showOrderList()
        })
      }
    },

    refund(row) {
      this.refundDialogVisible = true
      this.orderNo = row.orderNo
      this.paymentType = row.paymentType
      this.currentOrderTotalFee = row.totalFee || 0
      this.refundAmountYuan = Number(((row.totalFee || 1) / 100).toFixed(2))
      this.reason = '不喜欢'
    },

    showRefundRecords(row) {
      refundInfoApi.listByOrderNo(row.orderNo).then((response) => {
        this.refundRecordList = response.data.list || []
        this.refundRecordDialogVisible = true
      })
    },

    async checkPaymentStatus(row) {
      this.checkingPaymentOrderNo = row.orderNo
      try {
        const response = await orderInfoApi.checkPaymentStatus(
          row.orderNo,
          row.paymentChannelCode || row.paymentType
        )
        const nextStatus = response.data && (response.data.orderStatus || response.data.localStatus)
        if (nextStatus) {
          this.list = this.list.map(item => item.orderNo === row.orderNo
            ? { ...item, orderStatus: nextStatus }
            : item)
        }
        this.$message.success(nextStatus ? `支付状态：${nextStatus}` : '支付状态查询完成')
      } catch (_) {
        // request interceptor has already shown the server error.
      } finally {
        this.checkingPaymentOrderNo = ''
      }
    },

    async reconcileRefunds(row) {
      this.reconcilingOrderNo = row.orderNo
      try {
        const response = await refundInfoApi.reconcile(row.orderNo)
        this.refundRecordList = (response.data && response.data.list) || []
        this.refundRecordDialogVisible = true
        this.$message.success(response.message || '订单退款状态对账完成')
      } catch (_) {
        // request interceptor has already shown the server error.
      } finally {
        this.reconcilingOrderNo = ''
      }
    },

    closeDialog() {
      this.refundDialogVisible = false
      this.orderNo = ''
      this.reason = ''
      this.refundAmountYuan = 0.01
      this.currentOrderTotalFee = 0
      this.refundSubmitBtnDisabled = false
      this.paymentType = ''
    },

    toRefunds() {
      if (!this.refundAmountYuan || Number(this.refundAmountYuan) <= 0) {
        this.$message.error('请输入正确的退款金额')
        return
      }

      this.refundSubmitBtnDisabled = true
      const requestData = {
        orderNo: this.orderNo,
        refundAmount: Math.round(Number(this.refundAmountYuan) * 100),
        reason: this.reason || '正常退款'
      }

      const request = this.paymentType === '微信'
        ? wxPayApi.refunds(requestData)
        : aliPay.refunds(requestData)

      request.then((response) => {
        this.$message.success(response.message || '退款申请提交成功')
        this.closeDialog()
        this.showOrderList()
      }).catch(() => {
        this.refundSubmitBtnDisabled = false
      })
    },

    approvalStatusText(status) {
      const map = {
        PENDING: '待审核',
        APPROVED: '已通过',
        REJECTED: '已拒绝'
      }
      return map[status] || status || '-'
    },

    refundStatusText(status) {
      const map = {
        CREATED: '待处理',
        PROCESSING: '退款中',
        SUCCESS: '退款成功',
        FAILED: '退款失败',
        CLOSED: '已关闭',
        ABNORMAL: '退款异常'
      }
      return map[status] || status || '-'
    },

    approvalTagType(status) {
      const map = {
        PENDING: 'warning',
        APPROVED: 'success',
        REJECTED: 'info'
      }
      return map[status] || ''
    },

    refundTagType(status) {
      const map = {
        CREATED: 'warning',
        PROCESSING: 'danger',
        SUCCESS: 'success',
        FAILED: 'danger',
        CLOSED: 'info',
        ABNORMAL: 'danger'
      }
      return map[status] || ''
    }
  }
}
</script>

// springboot-payment/payment-demo-java/payment-demo-react/src/pages/Orders.jsx
import { useEffect, useRef, useState } from 'react'
import { Button, Empty, Form, InputNumber, message, Modal, Select, Table, Tag } from 'antd'

import aliPay from '@/api/aliPay'
import orderInfoApi from '@/api/orderInfo'
import wxPayApi from '@/api/wxPay'
import refundInfoApi from '@/api/refundInfo'
import { useAuth } from '@/auth/AuthContext'
import WxPayDialog from '@/components/WxPayDialog'

const APPROVAL_STATUS_TEXT = {
  PENDING: '待审核',
  APPROVED: '已通过',
  REJECTED: '已拒绝'
}

const REFUND_STATUS_TEXT = {
  CREATED: '待处理',
  PROCESSING: '退款中',
  SUCCESS: '退款成功',
  FAILED: '退款失败',
  CLOSED: '已关闭',
  ABNORMAL: '退款异常'
}

const APPROVAL_TAG_TYPE = {
  PENDING: 'warning',
  APPROVED: 'success',
  REJECTED: 'default'
}

const REFUND_TAG_TYPE = {
  CREATED: 'warning',
  PROCESSING: 'error',
  SUCCESS: 'success',
  FAILED: 'error',
  CLOSED: 'default',
  ABNORMAL: 'error'
}

function orderStatusTag(status) {
  const colorMap = {
    未支付: 'processing',
    支付成功: 'success',
    部分退款: 'warning',
    超时已关闭: 'warning',
    用户已取消: 'default',
    退款中: 'error',
    已退款: 'default',
    退款异常: 'error'
  }

  return <Tag color={colorMap[status]}>{status || '-'}</Tag>
}

export default function Orders() {
  const auth = useAuth()
  const isAdmin = auth.user?.role === 'ADMIN'
  const timerRef = useRef(null)
  const [list, setList] = useState([])
  const [loading, setLoading] = useState(true)
  const [itemsByOrder, setItemsByOrder] = useState({})
  const [payingOrderNo, setPayingOrderNo] = useState('')
  const [payDialog, setPayDialog] = useState({ open: false, codeUrl: '', orderNo: '' })
  const [refundDialogVisible, setRefundDialogVisible] = useState(false)
  const [refundRecordDialogVisible, setRefundRecordDialogVisible] = useState(false)
  const [refundRecordList, setRefundRecordList] = useState([])
  const [orderNo, setOrderNo] = useState('')
  const [reason, setReason] = useState('不喜欢')
  const [refundAmountYuan, setRefundAmountYuan] = useState(0.01)
  const [currentOrderTotalFee, setCurrentOrderTotalFee] = useState(0)
  const [refundSubmitBtnDisabled, setRefundSubmitBtnDisabled] = useState(false)
  const [paymentType, setPaymentType] = useState('')
  const [checkingPaymentOrderNo, setCheckingPaymentOrderNo] = useState('')
  const [reconcilingOrderNo, setReconcilingOrderNo] = useState('')

  const showOrderList = () => {
    setLoading(true)
    const request = auth.user?.role === 'ADMIN' ? orderInfoApi.list() : orderInfoApi.myList()
    request.then((response) => {
      setList(response?.data?.list || [])
    }).finally(() => setLoading(false))
  }

  useEffect(() => {
    showOrderList()
    return () => clearInterval(timerRef.current)
  }, [auth.user?.role])

  const loadItems = (expanded, row) => {
    if (!expanded || itemsByOrder[row.orderNo]) {
      return
    }
    orderInfoApi.items(row.orderNo).then((response) => {
      setItemsByOrder((current) => ({ ...current, [row.orderNo]: response?.data || [] }))
    })
  }

  const openWxPay = (response, targetOrderNo) => {
    setPayDialog({ open: true, codeUrl: response?.data?.codeUrl || '', orderNo: targetOrderNo })
    clearInterval(timerRef.current)
    timerRef.current = setInterval(() => {
      orderInfoApi.queryOrderStatus(targetOrderNo).then((status) => {
        if (status.code === 0) {
          clearInterval(timerRef.current)
          setPayDialog({ open: false, codeUrl: '', orderNo: '' })
          message.success('支付成功')
          showOrderList()
        }
      })
    }, 3000)
  }

  const retryPay = async (row, wxVersion = 'V3') => {
    setPayingOrderNo(row.orderNo)
    try {
      const channelCode = row.paymentChannelCode || (row.paymentType === '支付宝' ? 'ALIPAY' : 'WXPAY')
      if (channelCode === 'WXPAY') {
        const response = wxVersion === 'V2'
          ? await wxPayApi.nativePayV2Order(row.orderNo)
          : await wxPayApi.nativePayOrder(row.orderNo)
        openWxPay(response, row.orderNo)
      } else if (channelCode === 'ALIPAY') {
        const response = await aliPay.tradePagePayOrder(row.orderNo)
        document.open()
        document.write(response?.data?.formStr || '')
        document.close()
      } else {
        message.error('暂不支持该订单的支付渠道')
      }
    } finally {
      setPayingOrderNo('')
    }
  }

  const canApplyRefund = (orderStatus) => {
    return orderStatus === '支付成功' || orderStatus === '部分退款' || orderStatus === '退款中'
  }

  const cancel = (targetOrderNo, targetPaymentType) => {
    const request = targetPaymentType === '微信'
      ? wxPayApi.cancel(targetOrderNo)
      : aliPay.cancel(targetOrderNo)

    request.then((response) => {
      message.success(response.message || '取消成功')
      showOrderList()
    })
  }

  const refund = (row) => {
    setRefundDialogVisible(true)
    setOrderNo(row.orderNo)
    setPaymentType(row.paymentType)
    setCurrentOrderTotalFee(row.totalFee || 0)
    setRefundAmountYuan(Number(((row.totalFee || 1) / 100).toFixed(2)))
    setReason('不喜欢')
  }

  const showRefundRecords = (row) => {
    refundInfoApi.listByOrderNo(row.orderNo).then((response) => {
      setRefundRecordList(response?.data?.list || [])
      setRefundRecordDialogVisible(true)
    })
  }

  const checkPaymentStatus = async (row) => {
    setCheckingPaymentOrderNo(row.orderNo)
    try {
      const response = await orderInfoApi.checkPaymentStatus(
        row.orderNo,
        row.paymentChannelCode || row.paymentType
      )
      const nextStatus = response?.data?.orderStatus || response?.data?.localStatus
      if (nextStatus) {
        setList((current) => current.map((item) => (
          item.orderNo === row.orderNo ? { ...item, orderStatus: nextStatus } : item
        )))
      }
      message.success(nextStatus ? `支付状态：${nextStatus}` : '支付状态查询完成')
    } catch (_) {
      // request interceptor has already shown the server error.
    } finally {
      setCheckingPaymentOrderNo('')
    }
  }

  const reconcileRefunds = async (row) => {
    setReconcilingOrderNo(row.orderNo)
    try {
      const response = await refundInfoApi.reconcile(row.orderNo)
      setRefundRecordList(response?.data?.list || [])
      setRefundRecordDialogVisible(true)
      message.success(response.message || '订单退款状态对账完成')
    } catch (_) {
      // request interceptor has already shown the server error.
    } finally {
      setReconcilingOrderNo('')
    }
  }

  const closeDialog = () => {
    setRefundDialogVisible(false)
    setOrderNo('')
    setReason('')
    setRefundAmountYuan(0.01)
    setCurrentOrderTotalFee(0)
    setRefundSubmitBtnDisabled(false)
    setPaymentType('')
  }

  const toRefunds = () => {
    if (!refundAmountYuan || Number(refundAmountYuan) <= 0) {
      message.error('请输入正确的退款金额')
      return
    }

    setRefundSubmitBtnDisabled(true)

    const requestData = {
      orderNo,
      refundAmount: Math.round(Number(refundAmountYuan) * 100),
      reason: reason || '正常退款'
    }

    const request = paymentType === '微信'
      ? wxPayApi.refunds(requestData)
      : aliPay.refunds(requestData)

    request.then((response) => {
      message.success(response.message || '退款申请提交成功')
      closeDialog()
      showOrderList()
    }).catch(() => {
      setRefundSubmitBtnDisabled(false)
    })
  }

  const columns = [
    {
      title: '#',
      width: 50,
      render: (_, __, index) => index + 1
    },
    {
      title: '订单编号',
      dataIndex: 'orderNo',
      width: 230
    },
    {
      title: '订单标题',
      dataIndex: 'title'
    },
    {
      title: '订单金额',
      dataIndex: 'totalFee',
      render: (value) => `${(value || 0) / 100} 元`
    },
    {
      title: '支付方式',
      dataIndex: 'paymentType'
    },
    {
      title: '订单状态',
      dataIndex: 'orderStatus',
      render: orderStatusTag
    },
    {
      title: '操作',
      width: isAdmin ? 300 : 340,
      align: 'center',
      render: (_, row) => isAdmin ? (
        <>
          <Button
            type="link"
            loading={checkingPaymentOrderNo === row.orderNo}
            onClick={() => checkPaymentStatus(row)}
          >
            查询支付状态
          </Button>
          <Button
            type="link"
            loading={reconcilingOrderNo === row.orderNo}
            onClick={() => reconcileRefunds(row)}
          >
            对账退款
          </Button>
          <Button type="link" onClick={() => showRefundRecords(row)}>退款记录</Button>
        </>
      ) : (
        <>
          {row.orderStatus === '未支付' ? (
            <>
              <Button type="link" loading={payingOrderNo === row.orderNo} onClick={() => retryPay(row)}>重试支付</Button>
              {(row.paymentChannelCode === 'WXPAY' || row.paymentType === '微信') ? (
                <Button type="link" onClick={() => retryPay(row, 'V2')}>微信 V2</Button>
              ) : null}
              <Button type="link" onClick={() => cancel(row.orderNo, row.paymentType)}>取消</Button>
            </>
          ) : null}
          {canApplyRefund(row.orderStatus) ? (
            <Button type="link" onClick={() => refund(row)}>退款申请</Button>
          ) : null}
          <Button type="link" onClick={() => showRefundRecords(row)}>退款申请记录</Button>
        </>
      )
    }
  ]

  const refundRecordColumns = [
    {
      title: '退款申请单号',
      dataIndex: 'refundNo',
      width: 210
    },
    {
      title: '退款金额',
      dataIndex: 'refund',
      width: 110,
      render: (value) => `${(value || 0) / 100} 元`
    },
    {
      title: '审核状态',
      dataIndex: 'approvalStatus',
      width: 110,
      render: (status) => (
        <Tag color={APPROVAL_TAG_TYPE[status]}>
          {APPROVAL_STATUS_TEXT[status] || status || '-'}
        </Tag>
      )
    },
    {
      title: '退款状态',
      dataIndex: 'refundStatus',
      width: 110,
      render: (status) => (
        <Tag color={REFUND_TAG_TYPE[status]}>
          {REFUND_STATUS_TEXT[status] || status || '-'}
        </Tag>
      )
    },
    {
      title: '退款原因',
      dataIndex: 'reason'
    },
    {
      title: '审核备注',
      dataIndex: 'approveRemark'
    },
    {
      title: '申请时间',
      dataIndex: 'createTime',
      width: 170
    }
  ]

  return (
    <div className="bg-fa of">
      <section id="index" className="container">
        <header className="comm-title">
          <h2 className="fl tac">
            <span className="c-333">{auth.user?.role === 'ADMIN' ? '全部订单' : '我的订单'}</span>
          </h2>
        </header>
        <Table
          rowKey={(row) => row.orderNo}
          dataSource={list}
          columns={columns}
          bordered
          loading={loading}
          locale={{ emptyText: <Empty description="暂无订单" /> }}
          pagination={{ pageSize: 10 }}
          expandable={{
            onExpand: loadItems,
            expandedRowRender: (row) => {
              const items = itemsByOrder[row.orderNo] || []
              return items.length ? (
                <div className="order-items">
                  {items.map((item) => (
                    <div key={item.id || item.productId}>
                      <span>{item.productTitle}</span>
                      <span>¥{(item.unitPrice / 100).toFixed(2)} × {item.quantity}</span>
                      <strong>¥{(item.subtotal / 100).toFixed(2)}</strong>
                    </div>
                  ))}
                </div>
              ) : <span>正在读取订单明细...</span>
            }
          }}
        />
      </section>

      <Modal
        open={refundDialogVisible}
        width={420}
        centered
        title={null}
        onCancel={closeDialog}
        footer={[
          <Button key="cancel" onClick={closeDialog}>取 消</Button>,
          <Button key="submit" type="primary" onClick={toRefunds} disabled={refundSubmitBtnDisabled}>确 定</Button>
        ]}
      >
        <Form labelCol={{ span: 6 }} wrapperCol={{ span: 18 }}>
          <Form.Item label="订单编号">
            <span>{orderNo}</span>
          </Form.Item>
          <Form.Item label="订单金额">
            <span>{currentOrderTotalFee / 100} 元</span>
          </Form.Item>
          <Form.Item label="退款金额">
            <InputNumber
              value={refundAmountYuan}
              precision={2}
              step={0.01}
              min={0.01}
              max={currentOrderTotalFee / 100}
              controls
              style={{ width: '100%' }}
              onChange={(value) => setRefundAmountYuan(value || 0.01)}
            />
          </Form.Item>
          <Form.Item label="退款原因">
            <Select value={reason} placeholder="请选择退款原因" style={{ width: '100%' }} onChange={setReason}>
              <Select.Option value="不喜欢">不喜欢</Select.Option>
              <Select.Option value="买错了">买错了</Select.Option>
              <Select.Option value="其他">其他</Select.Option>
            </Select>
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="退款申请记录"
        open={refundRecordDialogVisible}
        width={900}
        centered
        footer={null}
        onCancel={() => setRefundRecordDialogVisible(false)}
      >
        <Table
          rowKey={(row) => row.refundNo}
          dataSource={refundRecordList}
          columns={refundRecordColumns}
          bordered
          pagination={false}
        />
      </Modal>

      <WxPayDialog
        open={payDialog.open}
        codeUrl={payDialog.codeUrl}
        onClose={() => {
          clearInterval(timerRef.current)
          setPayDialog({ open: false, codeUrl: '', orderNo: '' })
          showOrderList()
        }}
      />
    </div>
  )
}
