// springboot-payment/payment-demo-java/payment-demo-react/src/components/AppFooter.jsx
export default function AppFooter() {
  return (
    <footer id="footer">
      <section className="container">
        <div className="b-foot">
          <section className="fl col-7">
            <section className="mr20">
              <section className="b-f-link">
                <a href="#" title="关于我们" target="_blank" rel="noreferrer">关于我们</a>|
                <a href="#" title="联系我们" target="_blank" rel="noreferrer">联系我们</a>|
                <a href="#" title="帮助中心" target="_blank" rel="noreferrer">帮助中心</a>|
                <a href="#" title="资源下载" target="_blank" rel="noreferrer">资源下载</a>
                <span>Email：bytedance4j@163.com</span>
              </section>
            </section>
          </section>
          <div className="clear" />
        </div>
      </section>
    </footer>
  )
}

// springboot-payment/payment-demo-java/payment-demo-vue/src/components/AppFooter.vue
<template>
  <!-- 公共底 -->
  <footer id="footer">
    <section class="container">
      <div class="b-foot">
        <section class="fl col-7">
          <section class="mr20">
            <section class="b-f-link">
              <a href="#" title="关于我们" target="_blank">关于我们</a>|
              <a href="#" title="联系我们" target="_blank">联系我们</a>|
              <a href="#" title="帮助中心" target="_blank">帮助中心</a>|
              <a href="#" title="资源下载" target="_blank">资源下载</a>
              <span>Email：bytedance4j@163.com</span>
            </section>
          </section>
        </section>
        <div class="clear"/>
      </div>
    </section>
  </footer>
</template>
